### ISSUE TITLE
ImportError: cannot import name inplace_increment

### ISSUE THREAD

**Issue by ZhangXinNan** [KaiyangZhou/vsumm-reinforce#16]
```
(py27_theano0.9) zhangxin@zhangxin-AW:/media/zhangxin/DATA/github/vsumm-reinforce$ python vsum_test.py -model models/model_tvsum_reinforceRNN.h5 -d tvsum
Traceback (most recent call last):
  File "vsum_test.py", line 1, in <module>
    import theano
  File "/home/zhangxin/anaconda3/envs/py27_theano0.9/lib/python2.7/site-packages/theano/__init__.py", line 80, in <module>
    from theano.scan_module import (scan, map, reduce, foldl, foldr, clone,
  File "/home/zhangxin/anaconda3/envs/py27_theano0.9/lib/python2.7/site-packages/theano/scan_module/__init__.py", line 41, in <module>
    from theano.scan_module import scan_opt
  File "/home/zhangxin/anaconda3/envs/py27_theano0.9/lib/python2.7/site-packages/theano/scan_module/scan_opt.py", line 60, in <module>
    from theano import tensor, scalar
  File "/home/zhangxin/anaconda3/envs/py27_theano0.9/lib/python2.7/site-packages/theano/tensor/__init__.py", line 9, in <module>
    from theano.tensor.subtensor import *
  File "/home/zhangxin/anaconda3/envs/py27_theano0.9/lib/python2.7/site-packages/theano/tensor/subtensor.py", line 27, in <module>
    from cutils_ext.cutils_ext import inplace_increment
ImportError: cannot import name inplace_increment
```

**Comment by ZhangXinNan** [comment]
```
rm -rf ~/.theano
```
