### ISSUE TITLE
How to get the theano models?

### ISSUE THREAD

**Issue by meisa233** [KaiyangZhou/vsumm-reinforce#23]
The link is unavailable.
Can anyone help me?

**Comment by Junaid112** [comment]
after training via "vsum_train.py' model should be saved and you can use for inference. Did you train successfully or you are looking for already trained model?

**Comment by meisa233** [comment]
> after training via "vsum_train.py' model should be saved and you can use for inference. Did you train successfully or you are looking for already trained model?

Thanks for your reply. I am looking for already trained model in order to compare with my method.

**Comment by Junaid112** [comment]
I think there is no link to already trained model but I have just trained using pytorch implementation of this by same developer "https://github.com/KaiyangZhou/pytorch-vsumm-reinforce" so either you can train using the instruction or I can share trained model files.

**Comment by meisa233** [comment]
> I think there is no link to already trained model but I have just trained using pytorch implementation of this by same developer "https://github.com/KaiyangZhou/pytorch-vsumm-reinforce" so either you can train using the instruction or I can share trained model files.

Can you share your model?  Thank you very much.

**Comment by meisa233** [comment]
> I think there is no link to already trained model but I have just trained using pytorch implementation of this by same developer "https://github.com/KaiyangZhou/pytorch-vsumm-reinforce" so either you can train using the instruction or I can share trained model files.

I have trained my model using Theano with same results in this paper. Thanks for your reply.^ ^

**Comment by jayagupta678** [comment]
I am running "vsum_train.py' to regenerate model files, but getting following error message. please help me to recreate results used in the paper.

(bennett) C:\Users\Administrator\Downloads\vsumm-reinforce-master\vsumm-reinforce-master>python vsum_train.py
WARNING (theano.configdefaults): g++ not available, if using conda: `conda install m2w64-toolchain`
WARNING (theano.configdefaults): g++ not detected ! Theano will be unable to execute optimized C-implementations (for both CPU and GPU) and will default to Python implementations. Performance will be severely degraded. To remove this warning, set Theano flags cxx to an empty string.
[13/09/2021 06:20:40] model options: {'n_episodes': 5, 'input_dim': 1024, 'hidden_dim': 256, 'W_init': 'normal', 'U_init': 'normal', 'weight_decay': 1e-05, 'regularizer': 'L2', 'optimizer': 'adam', 'base_lr': 1e-05, 'decay_rate': 0.1, 'max_epochs': 60, 'decay_stepsize': -1, 'ignore_distant_sim': False, 'distant_sim_thre': 20, 'alpha': 0.01, 'model_file': None, 'disp_freq': 1, 'train_dataset_path': 'datasets/eccv16_dataset_summe_google_pool5.h5'}
[13/09/2021 06:20:40] initializing net model
Traceback (most recent call last):
  File "vsum_train.py", line 145, in <module>
    train(n_episodes=args.n_epi,
  File "vsum_train.py", line 59, in train
    net = reinforceRNN(model_options)
  File "C:\Users\Administrator\Downloads\vsumm-reinforce-master\vsumm-reinforce-master\model_reinforceRNN.py", line 37, in __init__
    self.fwd_rnn = LSTM(
  File "C:\Users\Administrator\Downloads\vsumm-reinforce-master\vsumm-reinforce-master\theano_nets.py", line 343, in __init__   
    self.output = self.step(self.state_below)
  File "C:\Users\Administrator\Downloads\vsumm-reinforce-master\vsumm-reinforce-master\theano_nets.py", line 393, in step       
    rval,_ = theano.scan(
  File "C:\Users\Administrator\anaconda3\envs\bennett\lib\site-packages\theano\scan_module\scan.py", line 1071, in scan
    scan_outs = local_op(*scan_inputs)
  File "C:\Users\Administrator\anaconda3\envs\bennett\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\Users\Administrator\anaconda3\envs\bennett\lib\site-packages\theano\scan_module\scan_op.py", line 568, in make_node  
    raise ValueError(err_msg2 %
ValueError: When compiling the inner function of scan the following error has been encountered: The initial state (`outputs_info` in scan nomenclature) of variable IncSubtensor{Set;:int64:}.0 (argument number 1) has dtype float32, while the result of the inner function (`fn`) has dtype float64. This can happen if the inner function of scan results in an upcast or downcast.
